# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 097e27173ea96ac23a111ca3cc2832101998222129332c92a2a5f64619a0c0ce1625bc2d880d4ca85a45b5444840ce669d96299dd0cd4f564a35709bd40dfd94

test:
  secret_key_base: 6552f8d927d1fc34ffd3c86bd93bbf1b561d965e39def349f4ddf583c4dcdbcb60ff500c285e1abd0f90cbc8a314f7779c484073fab4789cb3a294fcc9cdda60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
